In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [60]:
df = pd.read_csv(r"C:\Users\ksvra\Downloads\archive\netflix_titles.csv")
df.head(20)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
5,s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",The arrival of a charismatic young priest brin...
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,"September 24, 2021",2021,PG,91 min,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
8,s9,TV Show,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,"September 24, 2021",2021,TV-14,9 Seasons,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...
10,s11,TV Show,"Vendetta: Truth, Lies and The Mafia",NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, Docuseries, International TV S...","Sicily boasts a bold ""Anti-Mafia"" coalition. B..."
11,s12,TV Show,Bangkok Breaking,Kongkiat Komesiri,"Sukollawat Kanarot, Sushar Manaying, Pavarit M...",NaN,"September 23, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...","Struggling to earn a living in Bangkok, a man ..."
12,s13,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis Niewöhner, Milan Peschel, ...","Germany, Czech Republic","September 23, 2021",2021,TV-MA,127 min,"Dramas, International Movies",After most of her family is murdered in a terr...
13,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,"Klara Castanho, Lucca Picon, Júlia Gomes, Marc...",NaN,"September 22, 2021",2021,TV-PG,91 min,"Children & Family Movies, Comedies",When the clever but socially-awkward Tetê join...
14,s15,TV Show,Crime Stories: India Detectives,NaN,NaN,NaN,"September 22, 2021",2021,TV-MA,1 Season,"British TV Shows, Crime TV Shows, Docuseries",Cameras following Bengaluru police on the job ...
15,s16,TV Show,Dear White People,NaN,"Logan Browning, Brandon P. Bell, DeRon Horton,...",United States,"September 22, 2021",2021,TV-MA,4 Seasons,"TV Comedies, TV Dramas",Students of color navigate the daily slights a...
16,s17,Movie,Europe's Most Dangerous Man: Otto Skorzeny in ...,"Pedro de Echave García, Pablo Azorín Williams",NaN,NaN,"September 22, 2021",2020,TV-MA,67 min,"Documentaries, International Movies",Declassified documents reveal the post-WWII li...
17,s18,TV Show,Falsa identidad,NaN,"Luis Ernesto Franco, Camila Sodi, Sergio Goyri...",Mexico,"September 22, 2021",2020,TV-MA,2 Seasons,"Crime TV Shows, Spanish-Language TV Shows, TV ...",Strangers Diego and Isabel flee their home in ...
18,s19,Movie,Intrusion,Adam Salky,"Freida Pinto, Logan Marshall-Green, Robert Joh...",NaN,"September 22, 2021",2021,TV-14,94 min,Thrillers,After a deadly home invasion at a couple’s new...
19,s20,TV Show,Jaguar,NaN,"Blanca Suárez, Iván Marcos, Óscar Casas, Adriá...",NaN,"September 22, 2021",2021,TV-MA,1 Season,"International TV Shows, Spanish-Language TV Sh...","In the 1960s, a Holocaust survivor joins a gro..."

In [61]:
def columns_preprocessing(df,col):
    con = df[col].apply(lambda x: str(x).split(", ")).tolist()
    df_new1 = pd.DataFrame(con,index = df['title'])
    df_new1 = df_new1.stack()
    df_new1 = pd.DataFrame(df_new1.reset_index())
    df_new1.drop(['level_1'],axis=1,inplace=True)
    df_new1.rename(columns = {0:col},inplace = True)
    return df_new1

In [62]:
df_dir = columns_preprocessing(df,'director')
df_dir.head(20)

                                                title                director
0                                Dick Johnson Is Dead         Kirsten Johnson
1                                       Blood & Water                     nan
2                                           Ganglands         Julien Leclercq
3                               Jailbirds New Orleans                     nan
4                                        Kota Factory                     nan
5                                       Midnight Mass           Mike Flanagan
6                    My Little Pony: A New Generation           Robert Cullen
7                    My Little Pony: A New Generation          José Luis Ucha
8                                             Sankofa            Haile Gerima
9                       The Great British Baking Show         Andy Devonshire
10                                       The Starling          Theodore Melfi
11                Vendetta: Truth, Lies and The Mafia                     nan
12                                   Bangkok Breaking       Kongkiat Komesiri
13                                       Je Suis Karl     Christian Schwochow
14                   Confessions of an Invisible Girl           Bruno Garotti
15                    Crime Stories: India Detectives                     nan
16                                  Dear White People                     nan
17  Europe's Most Dangerous Man: Otto Skorzeny in ...  Pedro de Echave García
18  Europe's Most Dangerous Man: Otto Skorzeny in ...   Pablo Azorín Williams
19                                    Falsa identidad                     nan

In [63]:
df_cast = columns_preprocessing(df,'cast')
df_cast.rename(columns={'cast':'actors'},inplace=True)
df_cast.head()

                  title          actors
0  Dick Johnson Is Dead             nan
1         Blood & Water      Ama Qamata
2         Blood & Water     Khosi Ngema
3         Blood & Water   Gail Mabalane
4         Blood & Water  Thabang Molaba

In [64]:
df_listed =columns_preprocessing(df,'listed_in')
df_listed.head()

                  title               listed_in
0  Dick Johnson Is Dead           Documentaries
1         Blood & Water  International TV Shows
2         Blood & Water               TV Dramas
3         Blood & Water            TV Mysteries
4             Ganglands          Crime TV Shows

In [65]:
df_country = columns_preprocessing(df,'country')
df_country.head(20)

                                  title         country
0                  Dick Johnson Is Dead   United States
1                         Blood & Water    South Africa
2                             Ganglands             nan
3                 Jailbirds New Orleans             nan
4                          Kota Factory           India
5                         Midnight Mass             nan
6      My Little Pony: A New Generation             nan
7                               Sankofa   United States
8                               Sankofa           Ghana
9                               Sankofa    Burkina Faso
10                              Sankofa  United Kingdom
11                              Sankofa         Germany
12                              Sankofa        Ethiopia
13        The Great British Baking Show  United Kingdom
14                         The Starling   United States
15  Vendetta: Truth, Lies and The Mafia             nan
16                     Bangkok Breaking             nan
17                         Je Suis Karl         Germany
18                         Je Suis Karl  Czech Republic
19     Confessions of an Invisible Girl             nan

In [66]:
df_merge1 = df_cast.merge(df_dir,on=['title'],how = 'inner')
df_merge2 = df_merge1.merge(df_listed,on=['title'],how='inner')
df_new = df_merge2.merge(df_country,on=['title'],how='inner')
df_new.head()

,title,actors,director,listed_in,country
0,Dick Johnson Is Dead,nan,Kirsten Johnson,Documentaries,United States
1,Blood & Water,Ama Qamata,nan,International TV Shows,South Africa
2,Blood & Water,Ama Qamata,nan,TV Dramas,South Africa
3,Blood & Water,Ama Qamata,nan,TV Mysteries,South Africa
4,Blood & Water,Khosi Ngema,nan,International TV Shows,South Africa

In [67]:
df_new['actors'].replace(['nan'],['Unknown Actors'],inplace = True)
df_new['director'].replace(['nan'],['Unknown Director'],inplace = True)
df_new['country'].replace(['nan'],[np.nan],inplace = True)
df_new.head()

,title,actors,director,listed_in,country
0,Dick Johnson Is Dead,Unknown Actors,Kirsten Johnson,Documentaries,United States
1,Blood & Water,Ama Qamata,Unknown Director,International TV Shows,South Africa
2,Blood & Water,Ama Qamata,Unknown Director,TV Dramas,South Africa
3,Blood & Water,Ama Qamata,Unknown Director,TV Mysteries,South Africa
4,Blood & Water,Khosi Ngema,Unknown Director,International TV Shows,South Africa

In [68]:
df_final=df_new.merge(df[['show_id', 'type', 'title', 'date_added', 'release_year', 'rating', 'duration']],on=['title'],how='left')
df_final.head()

,title,actors,director,listed_in,country,show_id,type,date_added,release_year,rating,duration
0,Dick Johnson Is Dead,Unknown Actors,Kirsten Johnson,Documentaries,United States,s1,Movie,"September 25, 2021",2020,PG-13,90 min
1,Blood & Water,Ama Qamata,Unknown Director,International TV Shows,South Africa,s2,TV Show,"September 24, 2021",2021,TV-MA,2 Seasons
2,Blood & Water,Ama Qamata,Unknown Director,TV Dramas,South Africa,s2,TV Show,"September 24, 2021",2021,TV-MA,2 Seasons
3,Blood & Water,Ama Qamata,Unknown Director,TV Mysteries,South Africa,s2,TV Show,"September 24, 2021",2021,TV-MA,2 Seasons
4,Blood & Water,Khosi Ngema,Unknown Director,International TV Shows,South Africa,s2,TV Show,"September 24, 2021",2021,TV-MA,2 Seasons

In [69]:
df_final.isnull().sum()

title               0
actors              0
director            0
listed_in           0
country         11897
show_id             0
type                0
date_added        158
release_year        0
rating             67
duration            3
dtype: int64

In [70]:
#In duration column, it was observed that the nulls had values which were written in corresponding ratings column, i.e- you can't expect ratings to be in min. So the duration column nulls are replaced by corresponding values in ratings column

In [71]:
df_final.loc[df_final['duration'].isnull(),'duration'] = df_final.loc[df_final['duration'].isnull(),'duration'].fillna(df_final['rating'])
df_final.loc[df_final['rating'].str.contains('min',na = False),'rating'] = 'NR'
df_final['rating'].fillna('NR',inplace=True)
df_final.isnull().sum()

title               0
actors              0
director            0
listed_in           0
country         11897
show_id             0
type                0
date_added        158
release_year        0
rating              0
duration            0
dtype: int64

In [72]:
df_final[df_final['date_added'].isnull()]

,title,actors,director,listed_in,country,show_id,type,date_added,release_year,rating,duration
136893,A Young Doctor's Notebook and Other Stories,Daniel Radcliffe,Unknown Director,British TV Shows,United Kingdom,s6067,TV Show,NaN,2013,TV-MA,2 Seasons
136894,A Young Doctor's Notebook and Other Stories,Daniel Radcliffe,Unknown Director,TV Comedies,United Kingdom,s6067,TV Show,NaN,2013,TV-MA,2 Seasons
136895,A Young Doctor's Notebook and Other Stories,Daniel Radcliffe,Unknown Director,TV Dramas,United Kingdom,s6067,TV Show,NaN,2013,TV-MA,2 Seasons
136896,A Young Doctor's Notebook and Other Stories,Jon Hamm,Unknown Director,British TV Shows,United Kingdom,s6067,TV Show,NaN,2013,TV-MA,2 Seasons
136897,A Young Doctor's Notebook and Other Stories,Jon Hamm,Unknown Director,TV Comedies,United Kingdom,s6067,TV Show,NaN,2013,TV-MA,2 Seasons
...,...,...,...,...,...,...,...,...,...,...,...
186891,The Adventures of Figaro Pho,Charlotte Hamlyn,Unknown Director,TV Comedies,Australia,s8183,TV Show,NaN,2015,TV-Y7,2 Seasons
186892,The Adventures of Figaro Pho,Stavroula Mountzouris,Unknown Director,Kids' TV,Australia,s8183,TV Show,NaN,2015,TV-Y7,2 Seasons
186893,The Adventures of Figaro Pho,Stavroula Mountzouris,Unknown Director,TV Comedies,Australia,s8183,TV Show,NaN,2015,TV-Y7,2 Seasons
186894,The Adventures of Figaro Pho,Aletheia Burney,Unknown Director,Kids' TV,Australia,s8183,TV Show,NaN,2015,TV-Y7,2 Seasons
186895,The Adventures of Figaro Pho,Aletheia Burney,Unknown Director,TV Comedies,Australia,s8183,TV Show,NaN,2015,TV-Y7,2 Seasons

In [76]:
for i in df_final[df_final['date_added'].isnull()]['release_year'].unique():
  imp=df_final[df_final['release_year']==i]['date_added'].mode().values[0]
  df_final.loc[df_final['release_year']==i,'date_added']=df_final.loc[df_final['release_year']==i,'date_added'].fillna(imp)

In [77]:
df_final.isnull().sum()

title               0
actors              0
director            0
listed_in           0
country         11897
show_id             0
type                0
date_added          0
release_year        0
rating              0
duration            0
dtype: int64

In [79]:
for i in df_final[df_final['country'].isnull()]['director'].unique():
  if i in df_final[~df_final['country'].isnull()]['director'].unique():
    imp=df_final[df_final['director']==i]['country'].mode().values[0]
    df_final.loc[df_final['director']==i,'country']=df_final.loc[df_final['director']==i,'country'].fillna(imp)

In [81]:
df_final['country'].fillna('Unknown Country',inplace=True)
df_final.isnull().sum()

title           0
actors          0
director        0
listed_in       0
country         0
show_id         0
type            0
date_added      0
release_year    0
rating          0
duration        0
dtype: int64